version: "3.9"
services:
  postgresgin:
    image: postgres:latest
    container_name: postgresgin
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - ./app.env
    networks:
      - internal

  adminer:
    image: adminer
    ports:
      - "8181:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgresgin
    depends_on:
      - postgresgin
    networks:
      - internal

volumes:
  db:

networks:
  internal:
    driver: bridge